### ISSUE TITLE
Error running json2gv file

### ISSUE THREAD

**Issue by greyhoundforty** [l2fprod/vpc-diagram-exporter#5]
I am running in to an issue when trying to generate GraphViz files. This is occurring when using both the docker image as well as running the commands manually. 

```
~/Desktop/vpc-diagram-exporter (master ✔) ᐅ mac info
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G84

~/Desktop/vpc-diagram-exporter (master ✔) ᐅ which python3
/usr/local/bin/python3

~/Desktop/vpc-diagram-exporter (master ✔) ᐅ /usr/local/bin/python3 --version
Python 3.7.4

~/Desktop/vpc-diagram-exporter (master ✔) ᐅ pip3 install -r requirements.txt
Requirement already satisfied: sh in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.12.14)
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.10)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.3.9)
Requirement already satisfied: futures in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (3.1.1)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.7.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from Jinja2->-r requirements.txt (line 2)) (1.0)
Requirement already satisfied: click>=5.0 in /usr/local/lib/python3.7/site-packages (from python-dotenv->-r requirements.txt (line 5)) (7.0)
```

The `dump.py` command runs without issue 

```
~/Desktop/vpc-diagram-exporter (master ✔) ᐅ python3 dump.py
ibmcloud is floating-ips
ibmcloud is images
ibmcloud is ike-policies
ibmcloud is instances
ibmcloud is instance-profiles
ibmcloud is ipsec-policies
ibmcloud is keys
ibmcloud is load-balancers
ibmcloud is network-acls
ibmcloud is public-gateways
ibmcloud is regions
ibmcloud is security-groups
ibmcloud is subnets
ibmcloud is vpcs
ibmcloud is vpn-gateways
ibmcloud is volumes
ibmcloud is vpcs --classic-access
ibmcloud is zones eu-gb
ibmcloud is zones au-syd
ibmcloud is zones jp-tok
ibmcloud is zones eu-de
ibmcloud is zones us-south
ibmcloud is instance-network-interfaces 567292d2-627c-4407-82ea-9678f03acf9a
ibmcloud is instance-network-interfaces 244f070c-c5cf-4bdb-bcf6-1b2ebbadf8db
ibmcloud is instance-network-interfaces a499875d-0491-4a9e-91f1-75a4570bf34a
ibmcloud is vpn-gateway-connections adfb7362-e664-4299-8241-92189f0793a9
ibmcloud is vpn-gateway-connections 6e100926-c2a6-4f57-b317-45538ce87003
ibmcloud is vpc-address-prefixes edd05877-3358-425d-ac64-e7e11eea61e9
ibmcloud is vpc-address-prefixes 3ba21597-190d-49c7-9794-27652b5a0d27
ibmcloud is vpc-address-prefixes 16517c3e-e86c-47e9-bf83-e357a879185b
ibmcloud is vpc-address-prefixes 2be25f4f-0ba3-4759-8666-d7aca8240d71
ibmcloud is vpc-address-prefixes 8475a3d3-553c-4e72-b51d-6847ba84c2ae
~/Desktop/vpc-diagram-exporter (master ✔) ᐅ python3 dump.py
```

When I go to generate the GraphViz Diagrams however I get a `dict` error on `cpu`

```
~/Desktop/vpc-diagram-exporter (master ✔) ᐅ python3 json2gv.py
>>> Generating output/rt-vpc.gv
Traceback (most recent call last):
  File "json2gv.py", line 34, in <module>
    allOutputFile.write(template.render(data=all, styles=styles))
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 163, in top-level template code
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'cpu'
```

**Comment by l2fprod** [comment]
this one should be fixed now -- the template checks if the server has cpu or vcpu attributes
