### ISSUE TITLE
Error due to classic-access true or false flag

### ISSUE THREAD

**Issue by greyhoundforty** [l2fprod/vpc-diagram-exporter#7]
Just pulled the latest Docker image to test and see if my previous issue had been resolved. I am now seeing a new error as it seems the `/usr/local/bin/ibmcloud is vpcs --classic-access` call is missing the `true/false` flag:

```
tycho ◲ docker run --rm --volume $HOME:/home -it l2fprod/vpc-diagram-exporter
/home # ibmcloud login
API endpoint: https://cloud.ibm.com
(yada yada)

/home # ibmcloud is target --gen 1
OK
Target Generation: 1

/home # vpc-diagram-exporter
ibmcloud is floating-ips
ibmcloud is images
ibmcloud is ike-policies
ibmcloud is instances
ibmcloud is instance-profiles
ibmcloud is ipsec-policies
ibmcloud is keys
ibmcloud is load-balancers
ibmcloud is network-acls
ibmcloud is public-gateways
ibmcloud is regions
ibmcloud is security-groups
ibmcloud is subnets
ibmcloud is vpcs
ibmcloud is vpn-gateways
ibmcloud is volumes
ibmcloud is vpcs --classic-access
Traceback (most recent call last):
  File "/app/dump.py", line 48, in <module>
    all['vpcs'].extend(ibmcloudj('is', 'vpcs', '--classic-access'))
  File "/app/helpers.py", line 35, in ibmcloudj
    return json.loads(ibmcloud0(*args, json=True, **kwargs).stdout)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2:

  RAN: /usr/local/bin/ibmcloud is vpcs --classic-access --json

  STDOUT:
Listing vpcs for generation 1 compute in region us-south under account IBM as user rtiffany@us.ibm.com...
NAME:
    vpcs - List all VPCs

USAGE:
    /usr/local/bin/ibmcloud is vpcs [--classic-access true | false ] [--json]

OPTIONS:
   --classic-access value  This flag lists VPCs that have Classic access enabled. Enumeration type: true, false. If unspecified, it returns all VPCs with and without classic access enabled
   --json                  Format output in JSON

  STDERR:
FAILED
Incorrect Usage: options for classic-access are true, false
```

When running it manually it is the `json2gv.py` file again that is failing:

```
tycho ◲ python3 dump.py
ibmcloud is floating-ips
ibmcloud is images
ibmcloud is ike-policies
ibmcloud is instances
ibmcloud is instance-profiles
ibmcloud is ipsec-policies
ibmcloud is keys
ibmcloud is load-balancers
ibmcloud is network-acls
ibmcloud is public-gateways
ibmcloud is regions
ibmcloud is security-groups
ibmcloud is subnets
ibmcloud is vpcs
ibmcloud is vpn-gateways
ibmcloud is volumes
ibmcloud is vpcs --classic-access
ibmcloud is vpcs
ibmcloud is zones eu-gb
ibmcloud is zones au-syd
ibmcloud is zones jp-tok
ibmcloud is zones eu-de
ibmcloud is zones us-south
ibmcloud is instance-network-interfaces 60a61253-f289-4faf-a172-9657e54eedde
ibmcloud is instance-network-interfaces 08b5db0d-663a-4d07-8ed4-d004c7b830a4
ibmcloud is instance-network-interfaces f2f3a214-884a-4e2b-a31c-8df7c074c7f1
ibmcloud is instance-network-interfaces a84297c3-5c5e-451d-94c2-13f030e82676
ibmcloud is instance-network-interfaces 299d8c46-e7bd-42b3-b899-e6c0a32e66e2
ibmcloud is instance-network-interfaces d761a4d4-6fe1-4cea-aef5-fef1c90a8bc7
ibmcloud is instance-network-interfaces 00b1c877-e6bf-40e9-9d53-c8d63b54e098
ibmcloud is vpn-gateway-connections 66627acb-2b4e-477f-bb3a-1d9ee3dd13cc
ibmcloud is vpc-address-prefixes 8c4163cc-58e2-47f2-af6a-2fea5ec441e4
ibmcloud is vpc-address-prefixes 4c12f784-ebca-43c2-916d-11e6fb3b9a59
ibmcloud is vpc-address-prefixes 8c4163cc-58e2-47f2-af6a-2fea5ec441e4
ibmcloud is vpc-address-prefixes 4c12f784-ebca-43c2-916d-11e6fb3b9a59
python3 dump.py  33.58s user 29.35s system 150% cpu 41.858 total

tycho ◲ python3 json2gv.py
>>> Generating output/lonvpc-vpc.gv
>>> Generating output/rev1-vpc.gv
>>> Generating output/lonvpc-vpc.gv
>>> Generating output/rev1-vpc.gv
Traceback (most recent call last):
  File "json2gv.py", line 34, in <module>
    allOutputFile.write(template.render(data=all, styles=styles))
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 175, in top-level template code
TypeError: 'NoneType' object is not iterable
```

**Comment by greyhoundforty** [comment]
Per slack conversation, I tested the latest update and the issue has been resolved. 

```
>>> Generating output/iks-vpc.gv
>>> Generating output/tomcde.gv
>>> Generating output/dal-mathijs-test-vpc.gv
>>> Generating output/sa-dev.gv
>>> Generating output/fsvpctest.gv
/home #
```
